use_frameworks!

platform :ios, '9.0'

target 'UIKitBecaiOS_Example' do
  pod 'UIKitBecaiOS', :path => '../'

  target 'UIKitBecaiOS_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
