use_frameworks!

platform :ios, '9.0'

target 'UIKitBecaiOS_Example' do
  pod 'UIKitBecaiOS', :path => '../'
  pod 'UIKitBecaiOS', :git => 'https://https://github.com/KinhoA3M/UIKitBecaiOS'
  target 'UIKitBecaiOS_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
